name: 'Release Plugin'
description: 'Release GOG Galaxy integration on OS'

inputs:
  assets_dir:
    description: 'Location of directory containing build plugin artifacts (archives) for supported operating systems'
    required: true
    default: 'build'
  pre-release:
    description: 'Boolean indicating if Github release should be marked as pre-release'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'src/manifest.json'
        prop_path: 'version'
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.output-zip-name }}
        path: ${{ inputs.output-zip-name }}
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        # GitHub secret token
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Git tag (for automatic releases)
        automatic_release_tag: early_release_${{steps.version.outputs.prop}}
        # Should this release be marked as a pre-release?
        prerelease: True
        # Release title (for automatic releases)
        title: early_release_${{steps.version.outputs.prop}}
        # Assets to upload to the release
        files: uplay_win_afb5a69c-b2ee-4d58-b916-f4cd75d4999a.zip